import type { Transaction } from "~/core/types";

/** Mock transactions for development */
export const mockTransactions: Transaction[] = [
  {
    id: "TRX-001",
    event_id: "evt-1",
    event_name: "Adhyaksa FC vs Persija Jakarta",
    buyer_name: "Budi Santoso",
    buyer_email: "budi@email.com",
    buyer_phone: "081234567890",
    ticket_name: "Tribune Utara",
    quantity: 2,
    total_price: 150000,
    status: "paid",
    payment_method: "BCA Virtual Account",
    created_at: "2026-03-01T10:00:00Z",
  },
  {
    id: "TRX-002",
    event_id: "evt-1",
    event_name: "Adhyaksa FC vs Persija Jakarta",
    buyer_name: "Siti Rahayu",
    buyer_email: "siti@email.com",
    buyer_phone: "081234567891",
    ticket_name: "VIP",
    quantity: 1,
    total_price: 500000,
    status: "paid",
    payment_method: "GoPay",
    created_at: "2026-03-01T11:30:00Z",
  },
  {
    id: "TRX-003",
    event_id: "evt-2",
    event_name: "Adhyaksa FC vs Persib Bandung",
    buyer_name: "Ahmad Wijaya",
    buyer_email: "ahmad@email.com",
    ticket_name: "Tribune Selatan",
    quantity: 4,
    total_price: 300000,
    status: "pending",
    payment_method: "BRI Virtual Account",
    created_at: "2026-03-02T08:15:00Z",
  },
  {
    id: "TRX-004",
    event_id: "evt-1",
    event_name: "Adhyaksa FC vs Persija Jakarta",
    buyer_name: "Dewi Lestari",
    buyer_email: "dewi@email.com",
    ticket_name: "Tribune Barat",
    quantity: 3,
    total_price: 225000,
    status: "cancelled",
    created_at: "2026-02-28T14:00:00Z",
  },
  {
    id: "TRX-005",
    event_id: "evt-3",
    event_name: "Adhyaksa FC vs Arema FC",
    buyer_name: "Rudi Hermawan",
    buyer_email: "rudi@email.com",
    buyer_phone: "081234567893",
    ticket_name: "VIP",
    quantity: 2,
    total_price: 1000000,
    status: "paid",
    payment_method: "OVO",
    created_at: "2026-03-02T16:45:00Z",
  },
  {
    id: "TRX-006",
    event_id: "evt-2",
    event_name: "Adhyaksa FC vs Persib Bandung",
    buyer_name: "Maria Angelina",
    buyer_email: "maria@email.com",
    ticket_name: "Tribune Utara",
    quantity: 1,
    total_price: 75000,
    status: "refunded",
    created_at: "2026-02-27T09:00:00Z",
  },
  {
    id: "TRX-007",
    event_id: "evt-3",
    event_name: "Adhyaksa FC vs Arema FC",
    buyer_name: "Joko Susilo",
    buyer_email: "joko@email.com",
    ticket_name: "Tribune Selatan",
    quantity: 2,
    total_price: 150000,
    status: "paid",
    payment_method: "Dana",
    created_at: "2026-03-03T07:30:00Z",
  },
  {
    id: "TRX-008",
    event_id: "evt-1",
    event_name: "Adhyaksa FC vs Persija Jakarta",
    buyer_name: "Fitri Nuraini",
    buyer_email: "fitri@email.com",
    ticket_name: "Tribune Utara",
    quantity: 5,
    total_price: 375000,
    status: "paid",
    payment_method: "Mandiri Virtual Account",
    created_at: "2026-03-03T10:20:00Z",
  },
];
