import type { SelectOption } from "~/core/design-system/components";

export const INDONESIAN_CITY_OPTIONS: SelectOption[] = [
  { value: "Ambon", label: "Ambon" },
  { value: "Balikpapan", label: "Balikpapan" },
  { value: "Banda Aceh", label: "Banda Aceh" },
  { value: "Bandar Lampung", label: "Bandar Lampung" },
  { value: "Bandung", label: "Bandung" },
  { value: "Banjarmasin", label: "Banjarmasin" },
  { value: "Batam", label: "Batam" },
  { value: "Bekasi", label: "Bekasi" },
  { value: "Bogor", label: "Bogor" },
  { value: "Cilegon", label: "Cilegon" },
  { value: "Cimahi", label: "Cimahi" },
  { value: "Cirebon", label: "Cirebon" },
  { value: "Denpasar", label: "Denpasar" },
  { value: "Depok", label: "Depok" },
  { value: "Jakarta", label: "Jakarta" },
  { value: "Jambi", label: "Jambi" },
  { value: "Jayapura", label: "Jayapura" },
  { value: "Kediri", label: "Kediri" },
  { value: "Kupang", label: "Kupang" },
  { value: "Madiun", label: "Madiun" },
  { value: "Makassar", label: "Makassar" },
  { value: "Malang", label: "Malang" },
  { value: "Manado", label: "Manado" },
  { value: "Mataram", label: "Mataram" },
  { value: "Medan", label: "Medan" },
  { value: "Padang", label: "Padang" },
  { value: "Palangkaraya", label: "Palangkaraya" },
  { value: "Palembang", label: "Palembang" },
  { value: "Palu", label: "Palu" },
  { value: "Pekanbaru", label: "Pekanbaru" },
  { value: "Pontianak", label: "Pontianak" },
  { value: "Probolinggo", label: "Probolinggo" },
  { value: "Samarinda", label: "Samarinda" },
  { value: "Semarang", label: "Semarang" },
  { value: "Serang", label: "Serang" },
  { value: "Solo", label: "Solo" },
  { value: "Surabaya", label: "Surabaya" },
  { value: "Tangerang", label: "Tangerang" },
  { value: "Tangerang Selatan", label: "Tangerang Selatan" },
  { value: "Tasikmalaya", label: "Tasikmalaya" },
  { value: "Tegal", label: "Tegal" },
  { value: "Yogyakarta", label: "Yogyakarta" },
];
