import type { SelectOption } from "~/core/design-system/components";

export const INDONESIAN_PROVINCES = [
  "Aceh",
  "Sumatera Utara",
  "Sumatera Barat",
  "Riau",
  "Jambi",
  "Sumatera Selatan",
  "Bengkulu",
  "Lampung",
  "Kepulauan Bangka Belitung",
  "Kepulauan Riau",
  "DKI Jakarta",
  "Jawa Barat",
  "Jawa Tengah",
  "DI Yogyakarta",
  "Jawa Timur",
  "Banten",
  "Bali",
  "Nusa Tenggara Barat",
  "Nusa Tenggara Timur",
  "Kalimantan Barat",
  "Kalimantan Tengah",
  "Kalimantan Selatan",
  "Kalimantan Timur",
  "Kalimantan Utara",
  "Sulawesi Utara",
  "Sulawesi Tengah",
  "Sulawesi Selatan",
  "Sulawesi Tenggara",
  "Gorontalo",
  "Sulawesi Barat",
  "Maluku",
  "Maluku Utara",
  "Papua",
  "Papua Barat",
  "Papua Selatan",
  "Papua Tengah",
  "Papua Pegunungan",
  "Papua Barat Daya",
] as const;

export const SUPPORTED_NIK_CITIES = [
  "Aceh Selatan",
  "Ambon",
  "Banda Aceh",
  "Bandar Lampung",
  "Bandung",
  "Banjar",
  "Banjarmasin",
  "Bantul",
  "Banyumas",
  "Banyuwangi",
  "Barito Selatan",
  "Barito Timur",
  "Barito Utara",
  "Batam",
  "Batang",
  "Batu",
  "Bekasi",
  "Bogor",
  "Bukittinggi",
  "Cilacap",
  "Cilegon",
  "Cimahi",
  "Denpasar",
  "Depok",
  "Gunung Kidul",
  "Gunung Mas",
  "Jakarta Barat",
  "Jakarta Pusat",
  "Jakarta Selatan",
  "Jakarta Timur",
  "Jakarta Utara",
  "Jayapura",
  "Jember",
  "Jombang",
  "Kapuas",
  "Katingan",
  "Kediri",
  "Kepulauan Seribu",
  "Kotawaringin Barat",
  "Kotawaringin Timur",
  "Kudus",
  "Kulon Progo",
  "Lamandau",
  "Lebak",
  "Madiun",
  "Magelang",
  "Magetan",
  "Makassar",
  "Malang",
  "Manado",
  "Mojokerto",
  "Murung Raya",
  "Nganjuk",
  "Pacitan",
  "Padang",
  "Palangka Raya",
  "Palembang",
  "Pandeglang",
  "Pangkal Pinang",
  "Pekalongan",
  "Pekanbaru",
  "Pontianak",
  "Pulang Pisau",
  "Purwakarta",
  "Salatiga",
  "Samarinda",
  "Semarang",
  "Serang",
  "Seruyan",
  "Sidoarjo",
  "Sleman",
  "Sukabumi",
  "Sukamara",
  "Surabaya",
  "Surakarta",
  "Tangerang",
  "Tangerang Selatan",
  "Tanjung Pinang",
  "Tasikmalaya",
  "Tegal",
  "Yogyakarta",
] as const;

const LEGACY_DOMICILE_ALIASES: Record<string, string> = {
  jakarta: "DKI Jakarta",
  "daerah khusus jakarta": "DKI Jakarta",
  "daerah istimewa yogyakarta": "DI Yogyakarta",
  diy: "DI Yogyakarta",
  solo: "Surakarta",
  palangkaraya: "Palangka Raya",
};

export const HOME_DOMICILE_OPTIONS: SelectOption[] = [
  ...INDONESIAN_PROVINCES.map((province) => ({
    value: province,
    label: `${province} (Provinsi)`,
  })),
  ...SUPPORTED_NIK_CITIES.map((city) => ({
    value: city,
    label: `${city} (Kota/Kabupaten)`,
  })),
];

export function normalizeHomeDomicile(value: string | null | undefined): string {
  const trimmed = value?.trim() ?? "";
  return LEGACY_DOMICILE_ALIASES[trimmed.toLowerCase()] ?? trimmed;
}
